// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZtHWHycdS4SqAsQIgpijLmKuGdtD6cas',
    appId: '1:328451426723:web:5025660a24f0ab62bab216',
    messagingSenderId: '328451426723',
    projectId: 'weatherapp-f234d',
    authDomain: 'weatherapp-f234d.firebaseapp.com',
    storageBucket: 'weatherapp-f234d.firebasestorage.app',
    measurementId: 'G-L4BRRC9T6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Z4TmNFs370r6wHTLJgigIKskJQqqbtw',
    appId: '1:328451426723:android:7b5ddf79e1017e13bab216',
    messagingSenderId: '328451426723',
    projectId: 'weatherapp-f234d',
    storageBucket: 'weatherapp-f234d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfcMsdzWlwx1IgtZk782aXiEZNpnsse0A',
    appId: '1:328451426723:ios:ff43d86b3a659736bab216',
    messagingSenderId: '328451426723',
    projectId: 'weatherapp-f234d',
    storageBucket: 'weatherapp-f234d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfcMsdzWlwx1IgtZk782aXiEZNpnsse0A',
    appId: '1:328451426723:ios:ff43d86b3a659736bab216',
    messagingSenderId: '328451426723',
    projectId: 'weatherapp-f234d',
    storageBucket: 'weatherapp-f234d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZtHWHycdS4SqAsQIgpijLmKuGdtD6cas',
    appId: '1:328451426723:web:4bbae616ece02971bab216',
    messagingSenderId: '328451426723',
    projectId: 'weatherapp-f234d',
    authDomain: 'weatherapp-f234d.firebaseapp.com',
    storageBucket: 'weatherapp-f234d.firebasestorage.app',
    measurementId: 'G-TS6KP5X7SB',
  );
}
